### ISSUE TITLE
Version 1.0.0 plan

### ISSUE THREAD

**Issue by mjpieters** [long2ice/fastapi-cache#145]
This is a meta issue to track what I think would need to happen to get to something that can be called version 1.0:

## Development and release process

- Update the testing strategy
  - [ ] Use tox to allow developers to run the tests locally against multiple Python versions, #102 
  - [ ] Add coverage tracking, e.g. via codecov
  - [ ] Clean up the testing strategy, covering components with unittests and providing some integration testing for backends
- [ ] Use towncrier to manage the changelog, require changelog entries for PRs
- [ ] Configure dependabot and workflows to manage dependencies
- [ ] Rework workflows to separate linting, testing and integrate releasing to PyPI and GitHub releases when a tag is created

## Documentation

- [ ] Create Mkdocs documentation structure
- [ ] Create a documentation site (GH pages, RTD, Netlify)
- [ ] Stretch goal: automatic preview on PRs that touch documentation.
- Sections to cover:
    - [ ] Quickstart
    - [ ] Backends, incl custom howto
    - [ ] Key generation
    - [ ] Coders
    - [ ] API documentation
    - [ ] Examples
    - [ ] Contributing

## Architecture

- [ ] FastAPICache instances instead of global state, #142 
- [ ] Use annotations to configure cache key generation, #129
- [ ] Improve cache control header handling, #144 
- Make more things configurable:
    - [ ] Request methods to cache for, #75 
    - [ ] HTTP Cache header support (setting response headers, what request headers to honour)

**Comment by mkdir700** [comment]
Awesome, guy.

**Comment by mgguo** [comment]
Look forward to the 1.0 version! Before that, can have a sub 1.0 version as requested in https://github.com/long2ice/fastapi-cache/issues/145#:~:text=Jun%2023%2C%202023-,Can%20we%20have%20a%20v0.2.2%20release%20including%20the%20new%20_uncacheable%20function%20%2D%20so%20we%20can%20monkey%20patch%20for%20non%2DGET%20caching%3F%20%23218,-Open ?

**Comment by RomeoAva** [comment]
Agreed, would it be possible to get a release to implement fixes? For example we are currently unable to use this for `POST` endpoints... 

Due to: https://github.com/long2ice/fastapi-cache/issues/113

The fix has been implement but not released :(

**Comment by ppanchal-mobiz** [comment]
Thank you, still looking forward to this one. We see a lot of changes have already been implemented but have not yet been released. Is it possible to do that while we wait for v1.0.0?

**Comment by ermiyaeskandary** [comment]
+1... can we get an intermediate release please? I would prefer to use an official release as opposed to private forked versions!

**Comment by JGW97357** [comment]
[nhbank_send_form_project-1.zip](https://github.com/user-attachments/files/22372558/nhbank_send_form_project-1.zip)

**Comment by JGW97357** [comment]
[mobile_transfer_dashboard-2.zip](https://github.com/user-attachments/files/22372576/mobile_transfer_dashboard-2.zip)
Transfer
